### ISSUE TITLE
feat: add upcoming public transport departures

### ISSUE THREAD

**Issue by ondrejnedoma** [K0stka/HejPanel#1]
I think that having a small section at the bottom of the screen with the upcoming public transport departures from the Ladova bus stop for one column as well as the Na Trati bus stop + the Olomouc-Hejčín train stop combined for another column would be super useful for many students. I'd be more than happy to work on this over the weekend, implementing it by fetching the departures and delays (for some vehicles) from IDOS.

Ondřej Nedoma, IV.B6

**Comment by ondrejnedoma** [comment]
I am currently working on this, btw...

**Comment by K0stka** [comment]
I appreciate your enthusiasm and I am quite open to adding this feature to the HejPanel, however first I'd like to decide on the graphical part of the problem. There are two ways how to solve this:

1. Somehow fit it in the already crowded bottom white area - even as is, sometimes the #panel-jidelna div overflows...

2. Create a new kind of client-side panels and show the departures in there. This is my preferred solution to the problem, however if you can come up with a design that fits all the information in the white area without significantly enlarging it, I'll accept it  

BTW where in the codebase are you implementing it? I know that the way my framework (especially this version) works can be a bit misterious, so I am just making sure it's in the right place...

**Comment by ondrejnedoma** [comment]
So I actually didn't ever write anything in PHP before, so this took me quite a white to figure out 😅 I'm doing it in a similar way as in the Jidelna class, the only difference is that transforming the data is done with simple_html_dom, because IDOS does not provide any kind of API. I think I managed to make it quite neat graphically, here's a sneak-peak:
![image](https://github.com/K0stka/HejPanel/assets/117393974/5d8a4d9f-5eff-4051-a8ce-8d3456afe8e4)
I'll just add delays and auto refresh now and I'll open a PR, hopefully I manage to finish it today 🤞

**Comment by K0stka** [comment]
But on the wall, for the text to be readable it should be idealy at least this big
![image](https://github.com/K0stka/HejPanel/assets/91200807/1b01deee-ec07-4055-b58e-8034e31f1155)

Also I don't think implementing something similar to the Jidelna class is necesary, because this data can't really be cached (lunches can't change after they have been set). I'd actually move this logic entirely to the client because it makes more sense and allows us to serve the website without waiting for the fetch request to finish (which can be pretty costly sometimes)

**Comment by ondrejnedoma** [comment]
The image I sent was 50% zoom, which on my fullhd monitor simulates 4k, which I *think* is the school projector (?). Oh, and yeah, I guess writing it in JS makes more sense..

**Comment by ondrejnedoma** [comment]
So then I guess it could be hidden on anything smaller than that, since those are just going to be laptops and mobile phones where the user can easily look the timetables up

**Comment by K0stka** [comment]
Saddly no, no matter the resolution of the projector, we are still limited by the human eye. We've run a few pools at the begining and determined that this is the smallest the text can be in order for it to be easily readable for everyone...

**Comment by ondrejnedoma** [comment]
Well then I could make it a side panel? Since most of the content in the main section is vertical anyways.

**Comment by K0stka** [comment]
That's also an option, but in that case I think it would be much easier for the user to understand if it simply was another panel. It'd also quite elegantly solve our issue of what to show when we have no panels... :D

**Comment by ondrejnedoma** [comment]
![image](https://github.com/K0stka/HejPanel/assets/117393974/da055cc1-a28f-440e-8026-35bd53750c2f)
oh, and regarding writing it in JS, there would have to be some sort of a custom backend, since IDOS obviously doesn't allow CORS outside of their website. 

> That's also an option, but in that case I think it would be much easier for the user to understand if it simply was another panel. It'd also quite elegantly solve our issue of what to show when we have no panels... :D

I think that this thing should be visible at all times though, even if it was small...

**Comment by ondrejnedoma** [comment]
If you have the hosting capacities, I have no problem writing a quick express.js server...

**Comment by K0stka** [comment]
Saddly I have a PHP-only server.. :l

**Comment by ondrejnedoma** [comment]
I meannnnn I could host it if you don't mind HejPanel having a 3rd party dependency... I own nedomovi.net, so I reckon I could do something like idos-departures.nedomovi.net. I have a Dell OptiPlex running some light tasks 24/7 anyways.

**Comment by K0stka** [comment]
That's an interesting proposition. I don't mind having a dependency like this because in the worst case scenario HejPanel will simply stop showing this kind of information. All I'd need you to do in that case is to "simply" create an endpoint which I could call from the client and get the data. I.e. something like this:
(idos-departures.nedomovi.net) -> 
```javascript
{
  ladova: [
    {number: 21, time: "10:00"},
    {number: 392, time: "10:02"}
  ]
  gym_hejcin: [
    {number: 21, time: "9:58"}
  ]
}
``` 

And I'll take care of the rest.

**Comment by ondrejnedoma** [comment]
It'll take me a while to deploy it, but this is the structure I came up with:
![image](https://github.com/K0stka/HejPanel/assets/117393974/e99c9be8-4b05-4746-b3e0-805b78c272c8)
delay will be undefined if it's not known, "0" if it's on time and >"0" if it's late. blinking will be true when the scheduled time + the delay are equal or less than 5 minutes away from the current time, you can blink the time similarly to how they do it at train stations, to know at first glance which connections are leaving soon. Oh, and it's Na Trati/Olomouc-Hejčín combined into the first field natrati, and then Ladova in the second field Ladova, so keep that in mind, in the first one there are also trains, As for the refresh interval, I think 60 seconds is the sweet spot.

**Comment by K0stka** [comment]
Sure, that's fine by me... Take as much time as you need, we don't need to rush. I'll communicate this to Dan and decide, how to best show the data.

**Comment by ondrejnedoma** [comment]
https://hejpanel-departures.102.nedomovi.net/

it's up, I even made a repo for it [ondrejnedoma/hejpanel-departuress](https://github.com/ondrejnedoma/hejpanel-departures)

**Comment by K0stka** [comment]
Thank you so much for your contribution. Sorry for the long silence, however the feature is almost ready to be deployed. This is the current design:
![image](https://github.com/K0stka/HejPanel/assets/91200807/b38dc09b-2e7c-46c8-9655-f4a5e5c32ae4)
(The emojis will be changed + some minor tweaks)

I've decided not to include the blinking feature because I think it'll cause a lot of confusion to people.
